### ISSUE TITLE
Aspire 9.1 tries to start Lambda project and then debug option not available in Aspire dashboar

### ISSUE THREAD

**Issue by sjbthfc2** [aws/integrations-on-dotnet-aspire-for-aws#43]
Hi,

Just trying to have a play with the AWS Lambda hosting for Aspire 9.2([https://aws.amazon.com/blogs/developer/building-lambda-with-aspire-part-1/](url)) and I have added a Lambda Function (SQS trigger) and referenced it form the Apphost project. I have also added the pragma to allow preview methods but when I run the AppHost it fails because Aspire is trying to start the Lambda project which is a class library:

`"Status": "500 Internal Server Error", "Body": "A project with an Output Type of Class Library cannot be started directly.\r\n\r\nIn order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project."`

Is there some other configuration that has to be made, my addition of the Lambda project looks like:
`builder.AddAWSLambdaFunction<Projects.MonitorAndControl_EventHandler>("EventHandler", 
                                                                       lambdaHandler: "Me.MelCloudHome.MonitorAndControlService.EventHandler.FunctionHandler");`

I note a similar issue raised for Rider in the blog post but I am using Visual Studio 17.12.5.

Many Thanks and the Aspire support looks fantastic!

**Comment by normj** [comment]
There was an issue with the Visual Studio integration with Aspire that was triggering this issue that was fixed in a newer version. I'm currently running version `17.13.2`. Can you update your version of VS to the latest and see if the error reproduces? 

Here is the issue we worked with the .NET team to address this issue: https://github.com/dotnet/aspire/issues/6120#issuecomment-2542107118

**Comment by sjbthfc2** [comment]
Hi,

I have upgraded Visual Studio to 17.13.2 but I still get the same issue. Is it possible this is because I upgraded the Aspire App to 9.1 rather than created a new project, or is this solely a Visual Studio issue?

**Comment by normj** [comment]
Upgrading an existing project shouldn't matter. In the AppHost project is the `Sdk` element set to 9.1? For a class library Lambda function our integration writes a profile to the `launchsettings.json` file of the Lambda project. Can you that profile got written to the `launchsettings.json` file?

**Comment by philasmar** [comment]
Are you able to share the project with us so we can do some debugging?

**Comment by normj** [comment]
Closing for lack of activity. We have made some bug fixes in this area in the last few months which might have addressed the issue. If you come back to this issue and still find you are having the problem let us know.
